### PR TITLE
changed the background link to local files

### PR DESCRIPTION
**Pull request by abhijeetsingh-22**
Added the images in the public directory and changed the links to background in the css file

### CODE REVIEW

**Comment by HarishTeens** [comment]
@codemaster-abhi  you've linked the images but where are images?

**Comment by abhijeetsingh-22** [comment]
> @codemaster-abhi you've linked the images but where are images?

images are present in the public>stylesheets directory

**Comment by HarishTeens** [comment]
No the images should be in a separate directory public/images as mentioned before
And I don't see the images anywhere in Files Changed section , might be ignored somewhere , check it too

**Comment by abhijeetsingh-22** [comment]
> No the images should be in a separate directory public/images as mentioned before
> And I don't see the images anywhere in Files Changed section , might be ignored somewhere , check it too

I have updated the images directory in the public and also changed the background url. I have made a new pull request after updating files .

**Comment by HarishTeens** [comment]
@codemaster-abhi I think there is a miscommunication here, I dont see a new images directory being created under public folder

**Comment by HarishTeens** [comment]
Okay I'll close this PR now , just a note , you dont need to switch branch give different PR, pushing to the same automatically adds commit to that branch in PR

**Pull request closed without merging**
